version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-todo-nestjs
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./dist:/app/dist
    environment:
      - NODE_ENV=development
